src/Entity/Customer.php
<?php

namespace App\Entity;

use App\Repository\CustomerRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Symfony\Component\Uid\Uuid;

#[ORM\Entity(repositoryClass: CustomerRepository::class)]
class Customer
{
    #[ORM\Id]
    #[ORM\Column(type: UuidType::NAME, unique: true)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class: 'doctrine.uuid_generator')]
    private ?Uuid $id = null;

    #[ORM\Column(length: 255)]
    private ?string $name = null;

    #[ORM\Column(length: 255)]
    private ?string $address = null;

    #[ORM\Column(length: 10)]
    private ?string $postal_code = null;

    #[ORM\Column(length: 255)]
    private ?string $city = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $customer_number = null;

    #[ORM\Column(length: 255)]
    private ?string $email = null;

    #[ORM\OneToMany(mappedBy: 'customer', targetEntity: Invoice::class, orphanRemoval: true)]
    private Collection $quotes;

    #[ORM\OneToMany(mappedBy: 'customer', targetEntity: Invoice::class)]
    private Collection $invoices;

    #[ORM\OneToMany(mappedBy: 'customer', targetEntity: Payment::class)]
    private Collection $payments;

    #[ORM\ManyToOne(inversedBy: 'users')]
    private ?Company $company = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $phoneNumber = null;

    public function __construct()
    {
        $this->quotes = new ArrayCollection();
        $this->invoices = new ArrayCollection();
        $this->payments = new ArrayCollection();
    }

    public function getId(): ?Uuid
    {
        return $this->id;
    }

    public function setId(Uuid $id): static
    {
        $this->id = $id;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): static
    {
        $this->address = $address;

        return $this;
    }

    public function getPostalCode(): ?string
    {
        return $this->postal_code;
    }

    public function setPostalCode(string $postal_code): static
    {
        $this->postal_code = $postal_code;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): static
    {
        $this->city = $city;

        return $this;
    }

    public function getCustomerNumber(): ?string
    {
        return $this->customer_number;
    }

    public function setCustomerNumber(string $customer_number): static
    {
        $this->customer_number = $customer_number;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): static
    {
        $this->email = $email;

        return $this;
    }


    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): static
    {
        $this->company = $company;

        return $this;
    }

    /**
     * @return Collection<int, Invoice>
     */
    public function getQuotes(): Collection
    {
        return $this->quotes;
    }

    public function addQuote(Invoice $quote): static
    {
        if (!$this->quotes->contains($quote)) {
            $this->quotes->add($quote);
            $quote->setCustomer($this);
        }

        return $this;
    }

    public function removeQuote(Invoice $quote): static
    {
        if ($this->quotes->removeElement($quote)) {
            // set the owning side to null (unless already changed)
            if ($quote->getCustomer() === $this) {
                $quote->setCustomer(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Invoice>
     */
    public function getInvoices(): Collection
    {
        return $this->invoices;
    }

    public function addInvoice(Invoice $invoice): static
    {
        if (!$this->invoices->contains($invoice)) {
            $this->invoices->add($invoice);
            $invoice->setCustomer($this);
        }

        return $this;
    }

    public function removeInvoice(Invoice $invoice): static
    {
        if ($this->invoices->removeElement($invoice)) {
            // set the owning side to null (unless already changed)
            if ($invoice->getCustomer() === $this) {
                $invoice->setCustomer(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Payment>
     */
    public function getPayments(): Collection
    {
        return $this->payments;
    }

    public function addPayment(Payment $payment): static
    {
        if (!$this->payments->contains($payment)) {
            $this->payments->add($payment);
            $payment->setCustomer($this);
        }

        return $this;
    }

    public function removePayment(Payment $payment): static
    {
        if ($this->payments->removeElement($payment)) {
            // set the owning side to null (unless already changed)
            if ($payment->getCustomer() === $this) {
                $payment->setCustomer(null);
            }
        }

        return $this;
    }

    public function getPhoneNumber(): ?string
    {
        return $this->phoneNumber;
    }

    public function setPhoneNumber(?string $phoneNumber): static
    {
        $this->phoneNumber = $phoneNumber;

        return $this;
    }
}

src/Entity/Quote.php
<?php

namespace App\Entity;

use App\Entity\Traits\Timestampable;
use App\Repository\QuoteRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Types\UuidType;
use Symfony\Component\Uid\Uuid;

#[ORM\Entity(repositoryClass: QuoteRepository::class)]
class Quote
{
    use Timestampable;

    #[ORM\Id]
    #[ORM\Column(type: UuidType::NAME, unique: true)]
    #[ORM\GeneratedValue(strategy: 'CUSTOM')]
    #[ORM\CustomIdGenerator(class: 'doctrine.uuid_generator')]
    private ?Uuid $id = null;

    #[ORM\OneToMany(mappedBy: 'quote', targetEntity: QuoteItem::class, orphanRemoval: true, cascade:["persist"])]
    private Collection $quoteItems;

    #[ORM\ManyToOne(inversedBy: 'quotes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Customer $customer = null;

    #[ORM\ManyToOne(inversedBy: 'quotes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?QuoteStatus $status = null;


    #[ORM\ManyToOne(inversedBy: 'quotes')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Company $company = null;

    #[ORM\Column(length: 255)]
    private ?string $quoteNumber = null;

    #[ORM\OneToMany(mappedBy: 'quote', targetEntity: Invoice::class)]
    private Collection $invoices;


    public function __construct()
    {
        $this->quoteItems = new ArrayCollection();
        $this->invoices = new ArrayCollection();
    }

    public function getId(): ?Uuid
    {
        return $this->id;
    }

    public function setId(Uuid $id): static
    {
        $this->id = $id;

        return $this;
    }

    /**
     * @return Collection<int, QuoteItem>
     */
    public function getQuoteItems(): Collection
    {
        return $this->quoteItems;
    }

    public function addQuoteItem(QuoteItem $quoteItem): static
    {
        if (!$this->quoteItems->contains($quoteItem)) {
            $this->quoteItems->add($quoteItem);
            $quoteItem->setQuote($this);
        }

        return $this;
    }

    public function removeQuoteItem(QuoteItem $quoteItem): static
    {
        if ($this->quoteItems->removeElement($quoteItem)) {
            // set the owning side to null (unless already changed)
            if ($quoteItem->getQuote() === $this) {
                $quoteItem->setQuote(null);
            }
        }

        return $this;
    }

    public function getCustomer(): ?Customer
    {
        return $this->customer;
    }

    public function setCustomer(?Customer $customer): static
    {
        $this->customer = $customer;

        return $this;
    }

    public function getStatus(): ?QuoteStatus
    {
        return $this->status;
    }

    public function setStatus(?QuoteStatus $status): static
    {
        $this->status = $status;

        return $this;
    }


    public function getCompany(): ?Company
    {
        return $this->company;
    }

    public function setCompany(?Company $company): static
    {
        $this->company = $company;

        return $this;
    }

    public function getQuoteNumber(): ?string
    {
        return $this->quoteNumber;
    }

    public function setQuoteNumber(string $quoteNumber): static
    {
        $this->quoteNumber = $quoteNumber;

        return $this;
    }

    public function getTotalExcludingTax(): float
    {
        $total = 0.0;

        foreach ($this->getQuoteItems() as $quoteItem) {
            $total += $quoteItem->getPriceExcludingTax() * $quoteItem->getQuantity();
        }

        return $total;
    }

    /**
     * Calculate the tax amount for the quote.
     *
     * @return float The total tax amount.
     */
    public function getTaxAmount(): float
    {
        $total = 0.0;
        foreach ($this->getQuoteItems() as $quoteItem) {
            $total += $quoteItem->getTaxAmount() * $quoteItem->getQuantity();
        }
        return $total;
    }

    /**
     * Calculate the total amount including tax for all quote items.
     *
     * @return float The total amount including tax.
     */
    public function getTotalIncludingTax()
    {
        $total = 0.0;

        foreach ($this->getQuoteItems() as $quoteItem) {
            $total += $quoteItem->getPriceIncludingtax() * $quoteItem->getQuantity();
        }

        return $total;
    }

    /**
     * @return Collection<int, Invoice>
     */
    public function getInvoices(): Collection
    {
        return $this->invoices;
    }

    public function addInvoice(Invoice $invoice): static
    {
        if (!$this->invoices->contains($invoice)) {
            $this->invoices->add($invoice);
            $invoice->setQuote($this);
        }

        return $this;
    }

    public function removeInvoice(Invoice $invoice): static
    {
        if ($this->invoices->removeElement($invoice)) {
            // set the owning side to null (unless already changed)
            if ($invoice->getQuote() === $this) {
                $invoice->setQuote(null);
            }
        }

        return $this;
    }
}

templates/quote/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Plumbill
{% endblock %}

{% block body %}
    <main class="container mx-auto space-y-2 px-4 pt-4 md:px-0">
        <header class="flex justify-between flex-row">
            <h1 class="font-bold text-3xl">Liste des devis</h1>
            <a href="{{ path('quote_new') }}"
               class="font-semibold py-2 px-4 rounded border border-primary bg-primary text-white hover:bg-blue-dark hover:border-blue-dark dark:bg-blue-light/5 dark:border-primary/25 dark:hover:bg-primary/25">
                Créer un nouveau devis
            </a>
        </header>
        <section class="bg-white dark:bg-blue-darker flex gap-4 flex-wrap w-full p-4 shadow-md rounded-xl">
            <details class="font-bold cursor-pointer">
                <summary class="font-bold">Filtres</summary>
                {{ form_start(searchForm, {'method': 'POST', 'attr': {'class': 'animate-in fade-in duration-300'}}) }}
                {{ form_row(searchForm.status) }}
                {{ form_rest(searchForm) }}
                <button type="submit" id="quote_search_submit"
                        class="rounded px-2 py-1 bg-primary font-bold text-white disabled:bg-blue-lighter animate-in fade-in duration-300">
                    Filtrer
                </button>
                {{ form_end(searchForm) }}
            </details>
        </section>
        <section>
            {% if quotes|length == 0 %}
                <p class="mt-2">Aucun devis trouvé</p>
            {% endif %}
            <div class="w-full gap-2 grid grid-cols-1 md:grid-cols-2 md:gap-2 xl:grid-cols-4 xl:gap-3 2xl:grid-cols-4 2xl:gap-4">
                {% for quote in quotes %}
                    <twig:Quote:QuoteListItem :quote="quote"/>
                {% endfor %}
            </div>
        </section>
        <div class="navigation flex justify-center mb-8">
            {{ knp_pagination_render(quotes, 'components/TailwindPagination.html.twig') }}
        </div>
    </main>
    <script>
        const formEl = document.querySelector("form");
        const submitBtn = document.getElementById("quote_search_submit");
        submitBtn.disabled = isFormEmpty();

        formEl.addEventListener("input", function (e) {
            submitBtn.disabled = isFormEmpty();
        });

        function isFormEmpty() {
            let isEmpty = true;
            const fd = new FormData(formEl);

            for (const [key, value] of fd.entries()) {
                if (key.includes("_token")) continue;

                if (value.trim() !== '') {
                    isEmpty = false;
                    break;
                }
            }

            return isEmpty;
        }
    </script>

{% endblock %}

templates/quote/mail.html.twig
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Devis Reçue</title>
    <style>
        body { font-family: Arial, sans-serif; }
    </style>
</head>
<body>
    <p>Bonjour {{ quotes.customer.name }},</p>

    <p>Voici votre devis à cet email.</p>

    <p>Si vous avez des questions concernant ce devis ou avez besoin d'assistance supplémentaire, n'hésitez pas à nous contacter.</p>

    <p>Merci de faire affaire avec nous !</p>

    <p>Cordialement,<br>
    {{ quotes.company.name }}</p>
</body>
</html>

templates/quote/new_edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    {% if type == "new" %}
        Création de devis
    {% elseif type == "edit" %}
        Modification de devis
    {% endif %}

{% endblock %}

{% block body %}


    <header class="px-1 sm:px-0">
        <h1 class="text-3xl font-bold">
            {% if type == "new" %}
                Créer un nouveau devis
            {% elseif type == "edit" %}
                Modification de devis
            {% endif %}
        </h1>
    </header>
    <twig:Card class="space-y-2">
        <button onclick="openModal()"
                class="font-semibold py-2 px-4 rounded border border-primary bg-primary text-white hover:bg-blue-dark hover:border-blue-dark dark:bg-blue-light/5 dark:border-primary/25 dark:hover:bg-primary/25">
            Créer un client
        </button>
        {{ form_start(form) }}
        {{ form_row(form.customer) }}
        {{ form_row(form.status) }}
        <div id="quoteitem" data-prototype="{{ form_row(form.quoteitems.vars.prototype)|e('html_attr') }}">
            {{ form_row(form.quoteitems) }}
            <span id="lignesItems"></span>
        </div>
        {{ form_end(form) }}
    </twig:Card>
    <twig:Modal title="Ajout d'un client" id="clientModal">
        {% block form %}
            {{ form_start(customerForm, {'attr': {'id': 'customerForm', 'data-type': typeDocument}}) }}
            {{ form_row(customerForm.name) }}
            {{ form_row(customerForm.email) }}
            {{ form_row(customerForm.address) }}
            {{ form_row(customerForm.postal_code) }}
            {{ form_row(customerForm.city) }}

            <span class='flex gap-4 justify-end w-full mt-4'>
            {{ form_row(customerForm.submit) }}
            <button onclick="closeModal()"
                    class="font-bold py-2 px-4 rounded text-sm bg-error hover:bg-red-900 dark:hover:bg-red-dark text-white">
                Fermer
            </button>
        </span>
            {{ form_end(customerForm) }}
        {% endblock %}
    </twig:Modal>

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {{ encore_entry_script_tags('quotes') }}
    {{ encore_entry_script_tags('dropdown-customer') }}
{% endblock %}

templates/quote/pdf.html.twig
<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="UTF-8">
    <title>Devis {{ quotes.id }}</title>
     <style>
        body {
            font-family: Arial, sans-serif;
            
        }
        .title {
            font-size: 1.5rem;
            font-weight: bold;
            margin-bottom: 24px;
            text-shadow: 1px 1px 2px rgba(0,0,0,0.1); /* Ombrage léger pour le titre */
        }
        .section, .totals-row, .item-row {
            margin-bottom: 12px;
        }
        .section p, .totals-row, .item-row {
            font-size: 0.875rem;
        }
        .hr {
            border-top: 1px solid #4299e1;
            margin-top: 24px;
            margin-bottom: 24px;
        }
        table {
            width: 100%;
            border-collapse: collapse;
  
        }
        td {
            padding: 8px;
            text-shadow: 0.5px 0.5px 1px rgba(0,0,0,0.1); /* Ombrage léger pour le texte des cellules */
        }
        .totals-table {
            margin-top: 24px;
        }
        .totals-table td {
            text-align: right;
        }
        .header-row td {
            font-weight: bold;
        }
        .items {
            background: #f4f4f4;
            min-height: 450px;
        }
    </style>

</head>
<body>
<main>
    <h1 class="title">Devis n°{{ quotes.id }}</h1>
    <table>
        <tr>
            <td>
                <h3>Professionnel</h3>
                <p>{{ quotes.company.name }}</p>
                <p>{{ quotes.company.address }}</p>
                <p>{{ quotes.company.getPostalCode() }}, {{ quotes.company.city }}</p>
            </td>
            <td>
                <h3>Devis pour</h3>
                <p>{{ quotes.customer.name }}</p>
                <p>{{ quotes.customer.address }}</p>
                <p>{{ quotes.customer.getPostalCode() }}, {{ quotes.customer.city }}</p>
            </td>
        </tr>
    </table>
    <div class="section">
        <h3>Date du devis</h3>
        <p>{{ quotes.createdAt | date('d/m/Y') }}</p>
    </div>
    <hr class="hr">
    <table class="items">
        <tr class="header-row">
            <td>Description</td>
            <td>Quantité</td>
            <td>Prix Unitaire</td>
            <td>Tax</td>
            <td>Prix H.T</td>
            <td>Prix T.T.C</td>
        </tr>
        {% for item in quotes.quoteItems %}
        <tr class="item-row">
            <td>{{ item.service.name }}</td>
            <td>{{ item.quantity }}</td>
            <td>{{ item.priceExcludingTax|number_format(2, '.', ' ') }}€</td>
            <td>{{ item.tax.value }}%</td>
            <td>{{ (item.priceExcludingTax * item.quantity)|number_format(2, '.', ' ') }}€</td>
            <td>{{ (item.priceIncludingTax * item.quantity)|number_format(2, '.', ' ') }}€</td>
        </tr>
        {% endfor %}
    </table>
    <table class="totals-table" align="right">
        <tr class="totals-row">
            <td>Total H.T</td>
            <td>{{ quotes.getTotalExcludingTax|number_format(2, '.', ' ') }}€</td>
        </tr>
        <tr class="totals-row">
            <td>Total T.T.C</td>
            <td>{{ quotes.getTotalIncludingTax|number_format(2, '.', ' ') }}€</td>
        </tr>
    </table>
</main>
</body>
</html>

templates/quote/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Plumbill{% endblock %}

{% block body %}

    <header class="px-1 sm:px-0 flex justify-between items-center">
        <div class="flex items-center gap-4">
            <a href="{{ path('quote_index') }}"
               class="rounded-full hover:bg-grey-light/50 size-8 relative transition-all duration-200 cursor-pointer">
                <i class="material-symbols-outlined -translate-x-1/2 -translate-y-1/2 absolute top-1/2 left-1/2">arrow_left</i>
            </a>
            <h1 class="text-3xl md:text-4xl font-bold">Devis</h1>
        </div>
        <twig:Dropdown class="md:hidden" label="Gestion">
            {% block dropdownItems %}
                <a href="{{ path('quote_pdf', {'id': quote.id}) }}" target="_blank"
                   class="text-grey-dark block px-4 py-2 text-sm dark:text-white dark:hover:bg-grey-dark"
                   role="menuitem" tabindex="-1" id="menu-item-0">
                    Prévisualiser
                </a>
                {% if quote.status.name == 'accepted' %}
                    <a href="{{ path('quote_convert', {'id': quote.id}) }}"
                       class="text-grey-dark block px-4 py-2 text-sm dark:text-white dark:hover:bg-grey-dark"
                       role="menuitem" tabindex="-1" id="menu-item-1">
                        Convertir ce devis en facture
                    </a>
                {% elseif quote.status.name == 'draft' %}
                    <a href="{{ path('quote_sendpdf', {'id': quote.id}) }}"
                       class="text-grey-dark block px-4 py-2 text-sm dark:text-white dark:hover:bg-grey-dark"
                       role="menuitem" tabindex="-1" id="menu-item-1">
                        Envoyer le devis
                    </a>
                {% endif %}
                <a href="{{ path('quote_edit', {'id': quote.id}) }}"
                   class="text-grey-dark block px-4 py-2 text-sm dark:text-white dark:hover:bg-grey-dark"
                   role="menuitem" tabindex="-1" id="menu-item-2">
                    Modifier
                </a>
            {% endblock %}
        </twig:Dropdown>
        <div class="hidden md:flex gap-2 items-center h-fit">
            {% if quote.status.name != 'refused' %}
                <a href="{{ path('quote_pdf', {'id': quote.id}) }}" target="_blank"
                   class="text-center border border-primary bg-primary text-white hover:bg-blue-dark hover:border-blue-dark dark:bg-blue-light/5 dark:border-primary/25 dark:hover:bg-primary/25 rounded px-2 py-1 font-semibold text-sm flex items-center gap-1">
                    Prévisualiser
                    <i class="material-symbols-outlined">preview</i>
                </a>
            {% endif %}
            {% if quote.status.name == 'accepted' %}
                <a href="{{ path('quote_convert', {'id': quote.id}) }}"
                   class="text-center border border-primary bg-primary text-white hover:bg-blue-dark hover:border-blue-dark dark:bg-blue-light/5 dark:border-primary/25 dark:hover:bg-primary/25 rounded px-2 py-1 font-semibold text-sm flex items-center gap-1">
                    Convertir ce devis en facture
                    <i class="material-symbols-outlined">change_circle</i>
                </a>
            {% elseif quote.status.name == 'draft' %}
                <a href="{{ path('quote_sendpdf', {'id': quote.id}) }}"
                   class="text-center border border-primary bg-primary text-white hover:bg-blue-dark hover:border-blue-dark dark:bg-blue-light/5 dark:border-primary/25 dark:hover:bg-primary/25 rounded px-2 py-1 font-semibold text-sm flex items-center gap-1">
                    Envoyer le devis
                    <i class="material-symbols-outlined">send</i>
                </a>
            {% endif %}
            <a href="{{ path('quote_edit', {'id': quote.id}) }}"
               class="text-center border border-primary bg-primary text-white hover:bg-blue-dark hover:border-blue-dark dark:bg-blue-light/5 dark:border-primary/25 dark:hover:bg-primary/25 rounded px-2 py-1 font-semibold text-sm flex items-center gap-1">
                Modifier
                <i class="material-symbols-outlined">update</i>
            </a>
        </div>
    </header>
    <twig:Card>
        <h2 class="text-xl font-bold">Récapitulatif</h2>
        <div class="gap-1.5 w-full grid grid-cols-6">
            <section class="col-span-6 grid grid-cols-subgrid">
                <div class="col-span-5 flex flex-col">
                    <span class="text-grey-dark dark:text-grey text-xs uppercase font-medium leading-tight tracking-wide">Numéro de devis</span>
                    <span class="dark:text-grey-light font-bold leading-tight">{{ quote.quoteNumber }}</span>
                </div>
                <div class="col-span-1 flex flex-col">
                    <span class="text-grey-dark text-xs uppercase font-medium leading-tight tracking-wide">Statut</span>
                    <twig:StatusBadge :status="quote.status"/>
                </div>
            </section>
            <section class="col-span-6 grid grid-cols-subgrid">
                <div class="col-span-3 flex flex-col">
                    <span class="text-grey-dark dark:text-grey text-xs uppercase font-medium leading-tight tracking-wide">Nom du client</span>
                    <span class="dark:text-grey-light font-bold leading-tight">{{ quote.customer.name }}</span>
                </div>
                <div class="col-span-3 flex flex-col">
                    <span class="text-grey-dark dark:text-grey text-xs uppercase font-medium leading-tight tracking-wide">Numéro de client</span>
                    <span class="dark:text-grey-light font-bold leading-tight">{{ quote.customer.customerNumber }}</span>
                </div>
            </section>
            <section class="col-span-6 grid grid-cols-subgrid">
                <div class="col-span-3 flex flex-col">
                    <span class="text-grey-dark dark:text-grey text-xs uppercase font-medium leading-tight tracking-wide">Date de création</span>
                    <span class="dark:text-grey-light font-bold leading-tight">{{ quote.createdAt|date('d/m/Y') }}</span>
                </div>
            </section>
        </div>
    </twig:Card>
    <twig:Card class="flex-col">
        <div class="grid grid-cols-quote-items mb-2">
            <div class="grid grid-cols-subgrid col-span-4">
                <span class="font-semibold">Éléments</span>
                <span class="font-semibold justify-self-center">Qt</span>
                <span class="font-semibold justify-self-center">TVA</span>
                <span class="font-semibold justify-self-end">Total</span>
            </div>
            {% for item in quote.quoteItems %}
                <div class="grid grid-cols-subgrid col-span-4">
                    <span>{{ item.service.name }}</span>
                    <span class="justify-self-center">{{ item.quantity }}</span>
                    <span class="justify-self-end">{{ item.tax.value }}%</span>
                    <span class="justify-self-end">{{ (item.priceIncludingTax * item.quantity)|format_currency('EUR', locale='fr_FR') }}</span>
                </div>
            {% endfor %}
        </div>
        <div class="flex justify-end">
            <div class="border border-grey-light/5 rounded-sm px-2 py-1 w-1/2 flex flex-col">
                <div class="w-full md:w-fit gap-2 flex justify-between">
                    <span class="font-semibold">Sous-total</span>
                    <span>{{ quote.totalExcludingTax|format_currency('EUR', locale='fr_FR') }}</span>
                </div>
                <div class="w-full md:w-fit gap-2 flex justify-between">
                    <span class="font-semibold">TVA</span>
                    <span>{{ quote.taxAmount|format_currency('EUR', locale='fr_FR') }}</span>
                </div>
                <div class="w-full md:w-fit gap-2 flex justify-between">
                    <span class="font-semibold">TOTAL</span>
                    <span>{{ quote.totalIncludingTax|format_currency('EUR', locale='fr_FR') }}</span>
                </div>
            </div>
        </div>
    </twig:Card>
    <twig:Card>
        <h2 class="text-xl font-bold mb-2">Factures liées au devis</h2>
        <div class="w-full gap-2 grid grid-cols-1 md:grid-cols-2 md:gap-2 xl:grid-cols-4 xl:gap-3 2xl:grid-cols-4 2xl:gap-4">
            {% for invoice in invoices %}
                <twig:Invoice:InvoiceListItem :invoice="invoice"/>
            {% endfor %}
        </div>
    </twig:Card>
{% endblock %}